spring:
  application:
    name: ai-portfolio-analyser
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        options:
          model: gemini-3-flash-preview
      api-key: ${OPEN_AI_API_KEY}
  datasource:
    url: ${POSTGRES_CLOUD_URL}
    username: ${POSTGRES_CLOUD_USER}
    password: ${POSTGRES_CLOUD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
