name: ci-cd workflow
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'zulu'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=dev-praveen_ai-portfolio-analyser -DPOSTGRES_CLOUD_URL="${{ secrets.POSTGRES_CLOUD_URL }}" -DPOSTGRES_CLOUD_USER="${{ secrets.POSTGRES_CLOUD_USER }}" -DPOSTGRES_CLOUD_PASSWORD="${{ secrets.POSTGRES_CLOUD_PASSWORD }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build and push image to DockerHub
        run: mvn jib:build

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: ai-portfolio-analyser
          service-name: ai-portfolio-analyser-service
          docker: "docker.io/dockerpraveen123/portfolio-ai:latest"
          service-ports: "8080:http"
          service-routes: "/:8080"
          service-instance-type: 'small'
          service-regions: 'sin'
          service-env: "POSTGRES_CLOUD_URL=${{ secrets.POSTGRES_CLOUD_URL }},POSTGRES_CLOUD_USER=${{ secrets.POSTGRES_CLOUD_USER }},POSTGRES_CLOUD_PASSWORD=${{ secrets.POSTGRES_CLOUD_PASSWORD }}"